# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
---
- name: Retrieve all openstack images
  os_image_facts:

- name: Get image names and ids
  set_fact:
    image_facts: "{{ image_facts|default([]) + [{'name': item.name, 'id': item.id} ]}}"
  loop: '{{ openstack_image}}'
  when: item.name is defined

- name: Show images
  debug: 
    msg: "Image name: {{item.name}}; Image id: {{item.id}}"
  loop: '{{ image_facts }}'