# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
--- 
- name: Create snapshots of volume
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name}}'
    display_name: "{{ item.vol_name}}-{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S')}}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone}}'
  loop: '{{ volumes }}'