# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
---
# This is for git private setting etc. 
- name: Install npm
  become: yes
  apt: 
    name: ['npm']

- name: Copy front-end script
  copy: 
    src: front-end.sh
    dest: /home/ubuntu



- name: Run front-end script
  become: yes
  command: bash /home/ubuntu/front-end.sh '{{hostvars['localhost']['ip_facts'][0].address}}'
  register: output



  