---
# This is for git private setting etc. 
- name: Install npm
  become: yes
  apt: 
    name: ['npm']

- name: Copy front-end script
  copy: 
    src: front-end.sh
    dest: /home/ubuntu

# - name: Pause
#   pause: 
#     seconds: 10
- name: Run front-end script
  become: yes
  command: bash /home/ubuntu/front-end.sh
  