# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
---
- name: Git clone
  become: yes
  command: git clone https://'{{username}}':'{{password}}'@github.com/reporkey/CCC_ASS2-TheDeadlySins