---
- name: Add four proxies into etc environment
  become: yes
  command: bash -c '{{item}}'
  loop: '{{proxy_rule}}'

- name: Update apt-get
  become: yes
  apt: 
    upgrade: yes

- name: Install pip3
  become: yes
  apt: 
    name: ['python3-pip']
    # update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install pip2
  become: yes
  apt: 
    name: ['python-pip']
    # update_cache: yes
  when: ansible_distribution == "Ubuntu"


- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# Cannot install tweepy and curl. Since there is no pip3 module in ansible. 
- name: Install openstacksdk
  become: yes
  pip: 
    name: openstacksdk
    state: latest

- name: Install vim, git and docker.io
  become: yes
  apt:   
    name: '{{item}}'
  loop:
    - "git"
    - "docker.io"
    - "vim"

# - name: Configure docker internet setup
#   become: yes
#   command: mkdir /home/ubuntu/scripts

- name: Configuure docker internet setup
  become: yes
  copy: 
    src: docker-setup.sh
    dest: /home/ubuntu/

- name: Configure docker internet setup, pull couchdb.2.3.0
  become: yes
  command: bash /home/ubuntu/docker-setup.sh


# 或许这一步可以放到docker image里面?????
# - name: Configure docker internet connection. 
#   become: yes
#   command: bash -c 
  



