---
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: common
    - role: images
    - role: volume
    - role: security-groups
    - role: instance
    - role: snapshot