# - name: Format Volume
#   become: yes
#   filesystem:
#     fstype: ext4
#     dev: /dev/vdb

- name: Creatd Mount Directory
  become: yes
  file: 
    path: /data
    state: directory

- name: Mount Volume
  become: yes
  mount: 
    path: /data
    src: /dev/vdb
    fstype: ext4
    state: mounted

# - name: Copy mount-volume script
#   become: yes
#   copy: 
#     src: mount-volume.sh
#     dest: /home/ubuntu/

# - name: Mount Volume 
#   become: yes
#   command: bash /home/ubuntu/mount-volume.sh

    
# No sure how to run crawler.py
# - name: Copy crawler.py 
#   copy: 
#     src: /Users/Apple/Documents/Google-Sync/Cluster-and-Cloud-Computing/Project2/TwitterCrawler/tweetsCrawler.py
#     dest: /home/ubuntu/

# - name: Run crawler.py
#   become: yes
#   command: docker run --name tweetsdata -p 5984:5984 -v /data:/opt/couchdb/data -d couchdb:2.3.0
