# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
---
- name: Create an instance
  os_server: 
    name: '{{item}}'
    image: '{{ instance_image}}'
    key_name: '{{ instance_key_name}}'
    flavor: '{{instance_flavor}}'
    availability_zone: '{{ availability_zone}}'
    security_groups: '{{ sg_names}}'

    volumes: '{{volumes[in_index].vol_name}}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance 
  loop: "{{instance_name}}"
  loop_control:
    index_var: in_index

- name: debug
  debug: var=volumes



# - debug: var=os_instance

# - debug: var=ansible_facts  这个可以把当前运行的环境的facts提取出来. remote的还是拿不到
# - name: Add proxy into the new instance
#   file: path=/home/ubuntu/RealTimeCrawler state=directory
  

- debug: 
    msg: "Instance {{ item.openstack.name}} has been created. IP address is {{item.openstack.public_v4 }} "
  loop: "{{os_instance.results}}"
  # when: os_instance.openstack is defined
