# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
---
# Install dependencies on the host
- name: Install pip
  become: yes
  apt: 
    name: ['python-pip']
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get updte: sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip: 
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstack
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk