# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
--- 
- name: Create volume on NecTar
  os_volume:
    display_name: '{{ item.vol_name}}'
    size: '{{ item.vol_size}}'
    availability_zone: '{{ availability_zone}}'
    wait: yes
    timeout: 600 
    state: present
  loop: '{{ volumes}}'
  register: os_vol

- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [item.id]}}'
  loop: '{{os_vol.results}}'

- debug: 
    msg: "Volume {{ os_vol_ids}} has been created"
