# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes: 
  - vol_name: test-vol-1
    vol_size: 10
  - vol_name: test-vol-2
    vol_size: 10

# Security Groups

# security_groups:
#   - name: ssh
#   - name: http
#   - name: ICMP
#   - name: default

security_groups:
  - name: ssh
  - name: http
  - name: ICMP
  # - name: Automation_ssh
  #   description: "Security group for SSH access"
  #   protocol: tcp
  #   port_range_min: 22
  #   port_range_max: 22
  #   remote_ip_prefix: 0.0.0.0/0 #128.250.0.0/16
  # - name: Automation_http
  #   description: "Security group for HTTP"
  #   protocol: tcp
  #   port_range_min: 80
  #   port_range_max: 80
  #   remote_ip_prefix: 0.0.0.0/0
  # - name: Automation_icmp
  #   description: "Security group for ICMP"
  #   protocol: icmp
  #   remote_ip_prefix: 0.0.0.0/0
  #   port_range_min: 0
  #   port_range_max: 0



# Instance
instance_name: 
  - Automation_instance1
  - Automation_instance2
instance_image: 955a0556-1224-4499-a895-87d54d5cbf32
instance_key_name: tesft2
instance_flavor: uom.mse.2c9g

new_hosts_name:
  - name: Crawler1
  - name: Crawler2

    
