---
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: common
    - role: images
    - role: security-groups
    - role: instance

  tasks: 
    - name: Grab the ip addresses from new-built instances
      set_fact:
        ip_facts: "{{ip_facts|default([]) + [{'name': item.openstack.name, 'address': item.openstack.public_v4}]}}"
      loop: '{{ os_instance.results}}'
      when: item.openstack is defined
    - debug: var=ip_facts # ip_facts will be a list, containing 2 or 3 dictionaries(depending on the number of instances.)
    # - debug: var=


    - name: Pause and wait for instance creation 
      pause: 
        seconds: 90

    # From ip_facts, build a dynamic host in memory. 
    - name: Add dynamic hosts into inventory
      add_host: >
        name=dbserver groups=dbservers >
        ansible_host={{ip_facts[0].address}}
    - name: Add dynamic hosts into inventory
      add_host: >
        name=crawler-server groups=crawler-servers >
        ansible_host={{ip_facts[1].address}}
    - name: Add dynamic hosts into inventory
      add_host: >
        name=webserver groups=webservers >
        ansible_host={{ip_facts[2].address}}

    # - name: debug attaching. 
    - name: Gather server facts. 
      os_server_facts:
        server: web*
    - debug: var=openstack_servers

    # - debug: var=Automation-attatch
      # debug: var={{ hostvars['dbserver']['ansible_facts']}}

#Now build up remote server environment. 

- hosts: dbserver
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/github.yaml
  roles: 
    - role: env-setup
    - role: disk-mount
    - role: docker-setup


- hosts: crawler-server
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/github.yaml
  roles: 
    - role: env-setup
    - role: git-setup
    - role: crawler-setup
    
- hosts: webserver
  vars_files: 
    - host_vars/nectar.yaml
    - host_vars/github.yaml
  roles:
    - role: env-setup
    - role: git-setup
    - role: web-setup

    
