---
- name: Install docker.io
  become: yes
  apt:   
    name: '{{item}}'
  loop:
    - "docker.io"

- name: Configuure docker internet setup
  become: yes
  copy: 
    src: docker-setup.sh
    dest: /home/ubuntu/

- name: Configure docker internet setup, pull couchdb.2.3.0
  become: yes
  command: bash /home/ubuntu/docker-setup.sh

