# Project 2 for COMP90024 Cluster and Cloud Computing
# Team 3 
# Melbounrne
# Team Members and Student IDs
# Jingling Zhou 888137
# Xiaoyue Ma 878899
# Chengeng Liu 813174
# Yunxue Chen 905136
# Zichun Zhu 784145
--- 
- name: Create a list of security group names
  set_fact:
    sg_names: '{{ sg_names|default([]) + [item.name]}}'
  loop: '{{security_groups}}'

- debug:
    msg: "Security group(S) {{ sg_names }} have been created"
